# Conceptos básicos de NumPy



## Crear arreglos

En esta sección se trabajará con un Sudoku.

Como primer paso importe NumPy con el alias *np*

In [1]:
import numpy as np

Por el momento el Sudoku esta almacenado en una lista de Python llamada *sudoku_list*.

In [2]:
sudoku_list = [
    [0, 0, 4, 3, 0, 0, 2, 0, 9],
    [0, 0, 5, 0, 0, 9, 0, 0, 1],
    [0, 7, 0, 0, 6, 0, 0, 4, 3],
    [0, 0, 6, 0, 0, 2, 0, 8, 7],
    [1, 9, 0, 0, 0, 7, 4, 0, 0],
    [0, 5, 0, 0, 8, 3, 0, 0, 0],
    [6, 0, 0, 0, 0, 0, 1, 0, 5],
    [0, 0, 3, 5, 0, 8, 6, 9, 0],
    [0, 4, 2, 9, 1, 0, 3, 0, 0]
  ]


Convierta la lista de Python, en un arreglo de NumPy y almacenelo en una variable llamada *sudoku_array*.

In [3]:
sodoku_array = np.array(sudoku_list)
print(sodoku_array)

[[0 0 4 3 0 0 2 0 9]
 [0 0 5 0 0 9 0 0 1]
 [0 7 0 0 6 0 0 4 3]
 [0 0 6 0 0 2 0 8 7]
 [1 9 0 0 0 7 4 0 0]
 [0 5 0 0 8 3 0 0 0]
 [6 0 0 0 0 0 1 0 5]
 [0 0 3 5 0 8 6 9 0]
 [0 4 2 9 1 0 3 0 0]]


En ocasiones es necesario crear arreglos desde cero.

Para probar alguna de estas funciones cree un arreglo de ceros con 3 renglones y 4 columnas.

In [4]:
zeros_array = np.zeros((3,4))
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Dimensionalidad

Podemos modificar las dimensiones utilizando el método *reshape*.


Convierta el arreglo *sudoku_array* a un arreglo unidimensional, almacenelo en una variable llamada *sudoku_flatten* e imprimalo.

In [9]:
sudoku_flatten = sodoku_array.flatten()
print(sudoku_flatten)



[0 0 4 3 0 0 2 0 9 0 0 5 0 0 9 0 0 1 0 7 0 0 6 0 0 4 3 0 0 6 0 0 2 0 8 7 1
 9 0 0 0 7 4 0 0 0 5 0 0 8 3 0 0 0 6 0 0 0 0 0 1 0 5 0 0 3 5 0 8 6 9 0 0 4
 2 9 1 0 3 0 0]


Regrese el arreglo *sudoku_flatten* a las dimensiones originales y almacene el resultado en la variable *sudoku_reshaped*.

Imprima la variable sudoku_reshaped para observar que el orden de los elementos no se haya afectado.

In [10]:
sudoku_reshaped = sudoku_flatten.reshape(9, 9)
print(sudoku_reshaped)

[[0 0 4 3 0 0 2 0 9]
 [0 0 5 0 0 9 0 0 1]
 [0 7 0 0 6 0 0 4 3]
 [0 0 6 0 0 2 0 8 7]
 [1 9 0 0 0 7 4 0 0]
 [0 5 0 0 8 3 0 0 0]
 [6 0 0 0 0 0 1 0 5]
 [0 0 3 5 0 8 6 9 0]
 [0 4 2 9 1 0 3 0 0]]


## Tipos de dato

Imprima el tipo de dato del arreglo sudoku_array.

In [11]:
sodoku_array.dtype

dtype('int64')

Para optimizar memoria cambiemos el tipo de dato del arreglo *sudoku_array* a *uint8*

In [12]:
sodoku_array = sodoku_array.astype('uint8')
sodoku_array.dtype

dtype('uint8')

# Accediendo a elementos del arreglo

En esta sección se utilizará un arreglo con los datos de un censo de los árboles de Nueva York.

Esta es la informacion que contiene:
- La primer columna es el identificador del arbol.
- La segunda columna es el identificador del bloque al que pertenece el arbol.
- La tercer columna es el diametro del tronco.
- La cuarta columna es el diametro del tocón.

In [13]:
import numpy as np

Utilice la función `np.load()` para cargar los datos del archivo `tree_census.npy`.

Almacene el arreglo en una variable llamada `tree_census`

In [14]:
from google.colab import drive
drive.mount('/content/drive')

# Ruta al archivo en Google Drive
file_path = '/content/drive/My Drive/IAA/Practica2_CONCEPTOS BÁSICOS DE NUMPY/datasets/tree_census.npy'

# Cargar el archivo .npy
tree_census = np.load(file_path)

# Verifica el contenido
print(tree_census)


Mounted at /content/drive
[[     3 501451     24      0]
 [     4 501451     20      0]
 [     7 501911      3      0]
 ...
 [  1198 227387     11      0]
 [  1199 227387     11      0]
 [  1210 227386      6      0]]


Seleccione todos los renglones de la segunda columna (con indice 1) y almacenelos en una variable llamada *block_ids*

In [15]:
block_ids = tree_census[:, 1]


De la variable *block_ids* imprima:
- El octavo elemento.
- Todos los elementos hasta el sexto.
- 5 elementos empezando en el indice 10.

In [16]:
block_ids[7]
block_ids[:6]
block_ids[10:15]

array([501911, 501911, 501909, 501909, 501909])

Del arreglo *tree_census* selecciones todos los árboles (renglones) con un diametro del tronco menor a 10.

In [17]:
tree_census[tree_census[:, 2] < 10]

array([[     7, 501911,      3,      0],
       [     8, 501911,      3,      0],
       [     9, 501911,      4,      0],
       ...,
       [  1186, 226832,      0,     20],
       [  1187, 226832,      0,     21],
       [  1210, 227386,      6,      0]])

Investigadores descubrieron 2 nuevos árboles, ambos estan almacenados en la variable *new_trees*, agrege sus datos al arreglo *tree_census*

In [18]:
new_trees = np.array([[1211, 227386, 20, 0], [1212, 227386, 8, 0]])

In [19]:
tree_census = np.concatenate((tree_census, new_trees), axis=0)
print(tree_census)

[[     3 501451     24      0]
 [     4 501451     20      0]
 [     7 501911      3      0]
 ...
 [  1210 227386      6      0]
 [  1211 227386     20      0]
 [  1212 227386      8      0]]


# Operaciones con arreglos

En esta parte se utilizará un dataset que contiene las ventas mensuales de 3 empresas diferentes.

Cada renglon es un mes y cada columna es una empresa.

Los datos estan almacenados en la variable *monthly_sales*

In [20]:
import numpy as np


Utilizando la función `np.load()` lea el archivo `monthly_sales.npy` y almacene el resultado en una variable llamada `monthly_sales`.

In [21]:
from google.colab import drive
drive.mount('/content/drive')

# Ruta al archivo en Google Drive
file_path = '/content/drive/My Drive/IAA/Practica2_CONCEPTOS BÁSICOS DE NUMPY/datasets/monthly_sales.npy'

# Cargar el archivo .npy
monthly_sales = np.load(file_path)

# Verifica el contenido
print(monthly_sales)


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
[[ 4134 23925  8657]
 [ 4116 23875  9142]
 [ 4673 27197 10645]
 [ 4580 25637 10456]
 [ 5109 27995 11299]
 [ 5011 27419 10625]
 [ 5245 27305 10630]
 [ 5270 27760 11550]
 [ 4680 24988  9762]
 [ 4913 25802 10456]
 [ 5312 25405 13401]
 [ 6630 27797 18403]]


Obtenga el total de ventas de las 3 empresas por mes.

In [22]:
total_sales = np.sum(monthly_sales, axis=1)
print(total_sales)

[36716 37133 42515 40673 44403 43055 43180 44580 39430 41171 44118 52830]


Obtenga el total de ventas a final de año para cada empresa

In [23]:
total_sales_year = np.sum(monthly_sales, axis=0)
print(total_sales_year)

[ 59673 315105 135026]


Obtenga la suma acumulativa de ventas mensuales de cada empresa

In [24]:
total_sales_cumulative = np.cumsum(monthly_sales, axis=0)
print(total_sales_cumulative)

[[  4134  23925   8657]
 [  8250  47800  17799]
 [ 12923  74997  28444]
 [ 17503 100634  38900]
 [ 22612 128629  50199]
 [ 27623 156048  60824]
 [ 32868 183353  71454]
 [ 38138 211113  83004]
 [ 42818 236101  92766]
 [ 47731 261903 103222]
 [ 53043 287308 116623]
 [ 59673 315105 135026]]


Se desean calcular los impuestos de las ventas de cada mes por cada industria.

Para calcular el impuesto solo se necesita multiplicar el valor de las ventas por 0.05.

Obtenga los impuestos mensuales y alamcenelos en un arreglo llamado *tax_collected*

In [25]:
TAX_RATE = 0.05
tax_collected = monthly_sales * TAX_RATE
print(tax_collected)

[[ 206.7  1196.25  432.85]
 [ 205.8  1193.75  457.1 ]
 [ 233.65 1359.85  532.25]
 [ 229.   1281.85  522.8 ]
 [ 255.45 1399.75  564.95]
 [ 250.55 1370.95  531.25]
 [ 262.25 1365.25  531.5 ]
 [ 263.5  1388.    577.5 ]
 [ 234.   1249.4   488.1 ]
 [ 245.65 1290.1   522.8 ]
 [ 265.6  1270.25  670.05]
 [ 331.5  1389.85  920.15]]


Ahora obtenga el total de ingresos sumando el total de ventas de cada mes y el impuesto calculado de ese mes.

In [26]:
total_income = monthly_sales + tax_collected
print(total_income)

[[ 4340.7  25121.25  9089.85]
 [ 4321.8  25068.75  9599.1 ]
 [ 4906.65 28556.85 11177.25]
 [ 4809.   26918.85 10978.8 ]
 [ 5364.45 29394.75 11863.95]
 [ 5261.55 28789.95 11156.25]
 [ 5507.25 28670.25 11161.5 ]
 [ 5533.5  29148.   12127.5 ]
 [ 4914.   26237.4  10250.1 ]
 [ 5158.65 27092.1  10978.8 ]
 [ 5577.6  26675.25 14071.05]
 [ 6961.5  29186.85 19323.15]]


# Transformando arreglos (Opcional)

En esta última sección se aplicarán diferentes técnicas de transformación a la pintura *Paseo por el acantilado en Pourville* de Monet

Daremos permisos a Colab para acceder a Drive

Cargue el archivo llamado *rbg_array* y almacenelo en una variable con el mismo nombre.

In [27]:
import numpy as np

In [28]:
file_path = "" #complete la ruta de donde se leerá el archivo
with open(file_path, "rb") as f:
    rgb_array = np.load(f)

FileNotFoundError: [Errno 2] No such file or directory: ''

La siguiente celda de código permite visualizar la imagen

In [ ]:
from matplotlib import pyplot as plt
plt.imshow(rgb_array)

Utilizando el método *flip*, haga que el oceano se encuentre en la parte derecha de la imagen





utilizando el metodo *transpose* cambie el orden de renglones y columnas para girar la imagen 90°